name: Initialize input variables

on:
  workflow_call:
    outputs:
      BRANCH:
        description: "branch name"
        value: ${{ jobs.init-inputs.outputs.BRANCH }}

      ENVIRONMENT:
        description: "environment name"
        value: ${{ jobs.init-inputs.outputs.ENVIRONMENT }}      
          
 
jobs:
  init-inputs:
    runs-on: ubuntu-latest
    outputs:   
      BRANCH: ${{steps.initVars.outputs.BRANCH}}
      ENVIRONMENT: ${{steps.initVars.outputs.ENVIRONMENT}}
      
    steps:
    - name: initalize Inputs
      id: initVars
      run: |  
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.event_name }}
        
        if [[ "${{ github.ref_name }}" == *"develop" ]]; then
          echo "BRANCH=develop" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT=dev" >> "$GITHUB_OUTPUT"
      
        elif [[ "${{ github.ref_name }}" == *"main" ]]; then
          echo "BRANCH=main" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT=prod"  >> "$GITHUB_OUTPUT"      
        fi

    - name: Print the outputs
      run: |
        echo "BRANCH: ${{steps.initVars.outputs.BRANCH}}"
        echo "ENVIRONMENT: ${{steps.initVars.outputs.ENVIRONMENT}}"       